/*
Browse API

The Browse API has the following resources:<ul><li><b>item_summary:</b><br>Allows shoppers to search for specific items by keyword, GTIN, category, charity, product, image, or item aspects and refine the results by using filters, such as aspects, compatibility, and fields values, or UI parameters.</li><li><b>item:</b><br>Allows shoppers to retrieve the details of a specific item or all items in an item group, which is an item with variations such as color and size and check if a product is compatible with the specified item, such as if a specific car is compatible with a specific part.<br><br>This resource also provides a bridge between the eBay legacy APIs, such as the <a href=\"/api-docs/user-guides/static/finding-user-guide-landing.html\" target=\"_blank\">Finding</b>, and the RESTful APIs, which use different formats for the item IDs.</li></ul>The <b>item_summary</b>, <b>search_by_image</b>, and <b>item</b> resource calls require an <a href=\"/api-docs/static/oauth-client-credentials-grant.html\" target=\"_blank\">Application access token</a>.

API version: v1.19.9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package buybrowse

import (
	"encoding/json"
)

// checks if the AdditionalProductIdentity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdditionalProductIdentity{}

// AdditionalProductIdentity The type that defines the array of product identifiers associated with the item. This container is returned if the seller has associated the eBay Product Identifier (ePID) with the item, and in the request <code>fieldgroups</code> is set to <code>PRODUCT</code>.
type AdditionalProductIdentity struct {
	// An array of product identifier/value pairs for the product associated with the item. This is returned if the seller has associated the eBay Product Identifier (ePID) with the item and the request has <code>fieldgroups</code> set to <code>PRODUCT</code>.<br><br>The following table shows what is returned, based on the item information provided by the seller, when <code>fieldgroups</code> is set to <code>PRODUCT</code>.<br><br><div style=\"overflow-x:auto;\"><table border=1><tr><th>ePID Provided</th><th>Product ID(s) Provided</th><th>Response</th></tr><tr><td>No</td><td>No</td><td>The <code>AdditionalProductIdentity</code> container is <i>not</i> returned.</td></tr><tr><td>No</td><td>Yes</td><td>The <code>AdditionalProductIdentity</code> container is <i>not</i> returned but the product identifiers specified by the seller are returned in the <code>localizedAspects</code> container.</td></tr><tr><td>Yes</td><td>No</td><td>The <code>AdditionalProductIdentity</code> container is returned listing the product identifiers of the product.</td></tr><tr><td>Yes</td><td>Yes</td><td>The <code>AdditionalProductIdentity</code> container is returned listing all the product identifiers of the product and the product identifiers specified by the seller are returned in the <code>localizedAspects</code> container.</td></tr></table></div>
	ProductIdentity []ProductIdentity `json:"productIdentity,omitempty"`
}

// NewAdditionalProductIdentity instantiates a new AdditionalProductIdentity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdditionalProductIdentity() *AdditionalProductIdentity {
	this := AdditionalProductIdentity{}
	return &this
}

// NewAdditionalProductIdentityWithDefaults instantiates a new AdditionalProductIdentity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdditionalProductIdentityWithDefaults() *AdditionalProductIdentity {
	this := AdditionalProductIdentity{}
	return &this
}

// GetProductIdentity returns the ProductIdentity field value if set, zero value otherwise.
func (o *AdditionalProductIdentity) GetProductIdentity() []ProductIdentity {
	if o == nil || IsNil(o.ProductIdentity) {
		var ret []ProductIdentity
		return ret
	}
	return o.ProductIdentity
}

// GetProductIdentityOk returns a tuple with the ProductIdentity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdditionalProductIdentity) GetProductIdentityOk() ([]ProductIdentity, bool) {
	if o == nil || IsNil(o.ProductIdentity) {
		return nil, false
	}
	return o.ProductIdentity, true
}

// HasProductIdentity returns a boolean if a field has been set.
func (o *AdditionalProductIdentity) HasProductIdentity() bool {
	if o != nil && !IsNil(o.ProductIdentity) {
		return true
	}

	return false
}

// SetProductIdentity gets a reference to the given []ProductIdentity and assigns it to the ProductIdentity field.
func (o *AdditionalProductIdentity) SetProductIdentity(v []ProductIdentity) {
	o.ProductIdentity = v
}

func (o AdditionalProductIdentity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdditionalProductIdentity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProductIdentity) {
		toSerialize["productIdentity"] = o.ProductIdentity
	}
	return toSerialize, nil
}

type NullableAdditionalProductIdentity struct {
	value *AdditionalProductIdentity
	isSet bool
}

func (v NullableAdditionalProductIdentity) Get() *AdditionalProductIdentity {
	return v.value
}

func (v *NullableAdditionalProductIdentity) Set(val *AdditionalProductIdentity) {
	v.value = val
	v.isSet = true
}

func (v NullableAdditionalProductIdentity) IsSet() bool {
	return v.isSet
}

func (v *NullableAdditionalProductIdentity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdditionalProductIdentity(val *AdditionalProductIdentity) *NullableAdditionalProductIdentity {
	return &NullableAdditionalProductIdentity{value: val, isSet: true}
}

func (v NullableAdditionalProductIdentity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdditionalProductIdentity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


